### ISSUE TITLE
Not configured for 3rd parties to use, I think.

### ISSUE THREAD

**Issue by anyong** [nkoterba/material-design-iconsets#3]
I tried just following your instructions 'npm install', 'npm run init', 'npm run build'. First, the 'npm run init' command told me that there was a problem with 'gulp init', so I tried running that manually and there were three packages missing. gulp-print, gulp-rename, and gulp-insert. Then I tried npm run build and gulp is trying to download from my own local repository that this folder is in. I really would like to use these iconsets the way you have them set up, I'm just not sure how to get your package working.

**Comment by nkoterba** [comment]
@anyong I tested things several times before I originally uploaded things to github, but apparently something was amiss.

You are correct...gulp-print, gulp-rename, gulp-insert were missing from the package.json file.  I have since added them and re-tested and hopefully things work.

See: 0e7cec86d4

Let me know if you still have issues.  Thanks for the feedback.

Closing: #3
