### ISSUE TITLE
Problem with public:social

### ISSUE THREAD

**Issue by Stexxen** [nkoterba/material-design-iconsets#5]
Firstly, great repo. makes life a lot easier.

So, tried to use social:public and it wasn't working, so looked deeper and in social-icons.svg its being represented as 

```
<g id="publ24px.svg">
```

It is also represented this way even if I regenerate the iconsets. I suspect something wrong with Gulp, but alas my gulp-foo is weak.

**Comment by nkoterba** [comment]
@Stexxen Thanks for finding this bug.  I guess no one else has tried to use the public icon.  My regex was replacing `ic_` which starts each google Material Design icon name.  Unfortunately, `public_` also matches the Regex pattern and so it was getting replaced with empty string as well.

I've updated both the Regex as well as the Material Design Iconsets since Google (within last month) just added some new icons and also renamed others.

Potentially breaking changes.

Check out commit: 56e19938d8df9f5b16dc4c585c8215cf0b3e008d

Closing this issue as I believe things are now working.

Thanks again for filing an issue report!
